version: '3'
services:

  #Laravel App
  app:
    image: hosnol19/penilaian-docker:latest
    container_name: app
    restart: unless-stopped
    tty: true
    depends_on:
      - cache
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: hosnol19/penilaian-web_server:latest
    container_name: web_server
    restart: unless-stopped
    tty: true
    ports:
      - "8020:80"
    depends_on:
      - app
    networks:
      - app-network

  cache:
    image: redis:alpine
    container_name: cache
    restart: unless-stopped
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
